version: 1.0.{build}
configuration: Release
platform: Any CPU
# Install Pester
install: 
    - cinst -y pester
clone_folder: c:\projects\oneget
environment:
  PackageManagementManifest: c:\projects\oneget\output\release\bin\PackageManagement.psd1
build:
  verbosity: minimal
before_test:
- ps: >-
    Copy-Item -Recurse "c:\projects\oneget\Providers\Inbox\PowerShellGet" "$Env:ProgramFiles\WindowsPowerShell\Modules\" -Force -Verbose

    & "c:\projects\oneget\Test\run-tests.ps1"
