version: 1.0.{build}
os:
- WMF 5
environment:
  matrix:
    - test_framework: fullclr
    - test_framework: coreclr
configuration: Release
platform: Any CPU

init:

- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Install Pester
install: 
    - cinst -y pester
clone_folder: c:\projects\oneget
build_script:
- git submodule update --init
- ps: nuget locals all -clear
- ps: cd .\src; .\bootstrap.ps1; .\build.ps1 -framework "net451" Release; .\build.ps1 -framework "netstandard1.6" Release




deploy_script: 
  - ps: |
      Import-Module -Name c:\projects\oneget\tools\NewNuspec.psm1 -Force
      Set-Location C:\projects\oneget\src\out\PackageManagement
      # Creating NuGet package artifact
      New-Nuspec -packageName PackageManagement  -version $env:APPVEYOR_BUILD_VERSION -author "Microsoft" -owners "Microsoft" -licenseUrl "https://github.com/OneGet/oneget/blob/master/LICENSE" -projectUrl "https://oneget.org" -packageDescription $env:APPVEYOR_PROJECT_NAME -tags "PSEdition_Core PSEdition_Desktop Linux Mac PSModule" -destinationPath .
      nuget pack ".\PackageManagement.nuspec" -outputdirectory ..\.
      $nuGetPackageName = "PackageManagement." + $env:APPVEYOR_BUILD_VERSION + ".nupkg"

      @(
            # You can add other artifacts here
            "C:\projects\oneget\src\out\OneGet.FullClr.zip",
            "C:\projects\oneget\src\out\OneGet.CoreClr.zip",
            "C:\projects\oneget\src\out\$nuGetPackageName"
      ) | % { 
             Write-Host "Pushing package $_ as Appveyor artifact"
            Push-AppveyorArtifact $_
      }


test_script:
 - ps: >-
     & "c:\projects\oneget\Test\run-tests.ps1"
